### ISSUE TITLE
Finished

### ISSUE THREAD

**Issue by JodiDemir** [JodiDemir/kraken-good-accessibility#1]
@thatkidmadrid 
I got it to work in Markbot but I couldn't remember if I also had to tag you in an issue.

**Comment by thatkidmadrid** [comment]
Thanks! yes, by tagging me here I can provide some feedback that Markbot can't

For example, there's some alt attribute text missing to describe an important image on the page!
Every thing else looks well described and I see the roles where I would expect to see them and my voiceover checks look good

Make that change to the alt attribute text and I'll add the grade to LTW

**Comment by JodiDemir** [comment]
@thatkidmadrid 
I added the final alt description! 
Thanks!

**Comment by thatkidmadrid** [comment]
changed to green on LTW!
